title: Site
unlisted: true

tabs:
  pages:
    label: Pages
    preset: pages
    unlisted: true
    drafts:
      template: default
  header:
    fields:
      logoImage:
        label: Logo Image
        type: files
        layout: cards
        info: "{{ file.dimensions }}"
        template: cover
        min: 1
        max: 1
  footer:
    fields:
      footerText:
        label: Footer Text
        type: textarea
        size: small
      facebookPage:
        label: Facebook Page
        type: url
      twitterPage:
        label: Twitter Page
        type: url