title: Site
unlisted: true

tabs:
  pages:
    label: Pages
    preset: pages
    unlisted: true
    drafts:
      template: default
  header:
    fields:
      logoImage:
        label: Logo Image
        type: files
        layout: cards
        info: "{{ file.dimensions }}"
        multiple: false
        required: true
  footer:
    fields:
      footerText:
        label: Footer Text
        type: textarea
        size: small